name: Deploy Main (Production) Branch to Server - CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRODUCTION_HOST }}
          username: ${{ secrets.SSH_PRODUCTION_USERNAME }}
          password: ${{ secrets.SSH_PRODUCTION_PASSWORD }}
          port: ${{ secrets.SSH_PRODUCTION_PORT }}
          script: |
            cd ~/finance-tracking-bot
            git restore .
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 restart finance-tracking-bot || pm2 start npm --name "finance-tracking-bot" -- start
            pm2 save
